workflows:
  version_notify:
    name: Version Notify Pipeline
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: false
    scripts:
      - name: Echo Version
        script: |
          VERSION=$(cat VERSION 2>/dev/null || echo "1.0.0")
          echo "Version: $VERSION"
          echo $VERSION > version.txt
    artifacts:
      - version.txt
    publishing:
      slack:
        channel: "#sdk-release-updates"
        notify_on_build_start: false
        notify:
          success: true
          failure: true